mybatis:
    configuration:
        #   配置mybatis的日志，并输出到控制台
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        #开启驼峰命名
        map-underscore-to-camel-case: true
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/tlias
        username: root
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
